---
- name: Create Public DNS Entry
  route53:
    state: present
    overwrite: yes
    private_zone: no
    record: "{{ aws_instance.hostname_prefix }}.{{ unique_idm_name }}.{{ dns_domain }}"
    type: A
    ttl: 300
    value: "{{ eip.public_ip }}"
    zone: "{{ dns_domain }}."

- name: Create Private DNS Entry
  route53:
    state: present
    overwrite: yes
    private_zone: yes
    record: "{{ aws_instance.hostname_prefix }}.{{ unique_idm_name }}.{{ dns_domain }}"
    type: A
    ttl: 300
    value: "{{ ec2instance.tagged_instances[0].private_ip }}"
    zone: "{{ unique_idm_name + '.' + dns_domain }}."

- name: Breakout instance IP address
  set_fact:
    reverse_ips: "{{ ec2instance.tagged_instances[0].private_ip.split('.') }}"
  when: aws_instance.reverse_lookup

- name: Determine reverse lookup zone
  set_fact:
    reverse_zone: "{{ reverse_ips[-2] + '.' + reverse_ips[-3] + '.' + reverse_ips[-4] }}.in-addr.arpa."
  when: aws_instance.reverse_lookup

- name: Create Reverse Lookup Zone
  route53_zone:
    comment: "reverse lookup zone {{ reverse_zone }}"
    state: present
    vpc_id: "{{ vpc.vpcs[0].vpc_id }}"
    vpc_region: "{{ aws_region }}"
    zone: "{{ reverse_zone }}"
  when: aws_instance.reverse_lookup

- name: Create Reverse Lookup Entry
  route53:
    state: present
    overwrite: yes
    private_zone: yes
    record: "{{  reverse_ips[-1] + '.' + reverse_zone }}"
    type: PTR
    ttl: 300
    value: "{{ aws_instance.hostname_prefix }}.{{ unique_idm_name }}.{{ dns_domain }}"
    vpc_id: "{{ vpc.vpcs[0].vpc_id }}"
    zone: "{{ reverse_zone }}"
  when: aws_instance.reverse_lookup
