---
- name: Delete Public DNS Entry
  route53:
    state: absent
    private_zone: no
    record: "{{ aws_instance.hostname_prefix }}.{{ unique_idm_name }}.{{ dns_domain }}"
    type: A
    value: "{{ ec2instance.public_ip_address }}"
    ttl: 300
    zone: "{{ dns_domain }}."
  when: ec2instance is defined

- name: Delete Private DNS Entry
  route53:
    state: absent
    private_zone: yes
    record: "{{ aws_instance.hostname_prefix }}.{{ unique_idm_name }}.{{ dns_domain }}"
    type: A
    value: "{{ ec2instance.private_ip_address }}"
    ttl: 300
    zone: "{{ unique_idm_name + '.' + dns_domain }}."
  when: ec2instance is defined

- name: Breakout instance IP address
  set_fact:
    reverse_ips: "{{ ec2instance.private_ip_address.split('.') }}"
  when: aws_instance.reverse_lookup and ec2instance is defined

- name: Determine reverse lookup zone
  set_fact:
    reverse_zone: "{{ reverse_ips[-2] + '.' + reverse_ips[-3] + '.' + reverse_ips[-4] }}.in-addr.arpa."
  when: aws_instance.reverse_lookup and ec2instance is defined

- name: Delete Reverse Lookup Entry
  route53:
    state: absent
    private_zone: yes
    record: "{{  reverse_ips[-1] + '.' + reverse_zone }}"
    type: PTR
    value: "{{ aws_instance.hostname_prefix }}.{{ unique_idm_name }}.{{ dns_domain }}"
    ttl: 300
    vpc_id: "{{ vpc.vpcs[0].vpc_id }}"
    zone: "{{ reverse_zone }}"
  when: aws_instance.reverse_lookup and ec2instance is defined

- name: Delete Reverse Lookup Zone
  route53_zone:
    state: absent
    vpc_id: "{{ vpc.vpcs[0].vpc_id }}"
    vpc_region: "{{ aws_region }}"
    zone: "{{ reverse_zone }}"
  when: aws_instance.reverse_lookup
